# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'yarn'
    - name: Install packages
      run: yarn
    - name: Run deploy
      run: git remote add heroku https://git.heroku.com/notifica-ufba.git
    - run: git config user.email "igoor1205@gmail.com"
    - run: git config user.name "igoor1205@gmail.com"
    - run: git push heroku master
